/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ChronologyListItem: typeof import('./src/components/ChronologyListItem.vue')['default']
    ContributionsToPeriodicalsListItem: typeof import('./src/components/ContributionsToPeriodicalsListItem.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    IconBack: typeof import('./src/components/icons/IconBack.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconLogo: typeof import('./src/components/icons/IconLogo.vue')['default']
    IconMoon: typeof import('./src/components/icons/IconMoon.vue')['default']
    IconMusic: typeof import('./src/components/icons/IconMusic.vue')['default']
    IconMusical: typeof import('./src/components/icons/IconMusical.vue')['default']
    IconPlus: typeof import('./src/components/icons/IconPlus.vue')['default']
    IconSun: typeof import('./src/components/icons/IconSun.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconVideo: typeof import('./src/components/icons/IconVideo.vue')['default']
    ImageViewerModal: typeof import('./src/components/ImageViewerModal.vue')['default']
    LoadingComponent: typeof import('./src/components/LoadingComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TranslationModal: typeof import('./src/components/TranslationModal.vue')['default']
    UploadItem: typeof import('./src/components/UploadItem.vue')['default']
  }
}
